version: '3'

services:
  ################################
  # Pytest on CRUD functions
  ################################
  crud-pytest:
    container_name: crud-pytest
    build:
      context: .
      dockerfile: docker/Dockerfile.test