version: '3'
volumes:
  rabbitmq_data:
  mongo_data:
services:
  ################################
  # RabbitMQ: Message Broker
  ################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  ################################
  # MongoDB: Database
  ################################
  mongo:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  ################################
  # Mongo Express: Database GUI
  ################################
  # mongo-express:
  #   image: mongo-express:latest
  #   container_name: mongo-express
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     - mongo
  #   networks:
  #     - my-network

  ################################
  # ImageBuilder: App Service
  ################################
  image-builder:
    build:
      context: ./
      dockerfile: docker/Dockerfile.dev
    image: image-builder:1.0
    depends_on:
      - rabbitmq
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock
    privileged: true

networks:
  my-network:
    driver: bridge

