FROM gcr.io/kaniko-project/executor:latest AS kaniko

FROM python:3.11-slim

ENV DOCKER_CONFIG /kaniko/.docker

COPY --from=kaniko /kaniko /kaniko


# Update pip and clean up cache to reduce image size
RUN pip3 install --upgrade pip
RUN rm -rf /var/cache/apk/*

# Set the working directory in the container
WORKDIR /usr/image_builder

# Copy your application code into the container
COPY ./ /usr/image_builder/

# Create the image_to_build directory
RUN mkdir image_to_build

# Optionally, install Python packages using pip
RUN pip3 install --no-cache-dir -r requirements.txt

# Run the app
CMD ["python3", "src/main.py"]
