FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /usr/image_builder_test

# Copy your application code into the container
COPY ../ /usr/image_builder_test/

# Install Python dependencies using pip
RUN pip install --no-cache-dir -r requirements.txt

# Install test dependencies using pip
RUN pip install --no-cache-dir -r ./requirements.test.txt

# Specify the command to run your tests
CMD ["python3", "-m", "pytest"]